version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: banking_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: banking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512m

  redis:
    image: redis:7
    container_name: banking_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 256m

  mongo:
    image: mongo:7
    container_name: banking_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345
    ports:
      - "27017:27017"
    command: ["--wiredTigerCacheSizeGB", "0.25"] 
    deploy:
      resources:
        limits:
          memory: 512m

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: banking_otel_collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317" # gRPC
      - "4318:4318" # HTTP
    restart: unless-stopped

volumes:
  postgres_data:
