version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: banking_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: banking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: banking_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  mongo:
    image: mongo:7
    container_name: banking_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345
    ports:
      - "27017:27017"

volumes:
  postgres_data: