spring:
  profiles:
    active: dev

  main:
    web-application-type: servlet

  config:
    import: "optional:configserver:"

  cloud:
    discovery:
      enabled: false

eureka:
  client:
    enabled: false

management:
  metrics:
    export:
      otlp:
        enabled: true
        step: 30s                  
        url: http://localhost:4318/v1/metrics